### ISSUE TITLE
Filter injection in Scaldi

### ISSUE THREAD

**Issue by albertshift** [scaldi/scaldi-play-example#6]
I am trying to implement BasicAuthFilter, that's because I need to check all requests by using authentication.
For this purpose I created Global object:

```
object Global extends WithFilters(BasicAuthFilter) with GlobalSettings with LazyLogging {

    override def onStart(app: Application) {
      logger.info("Application has started")
    }  
  
    override def onStop(app: Application) {
      logger.info("Application shutdown...")
    }  
    
  
}
```

And BasicAuthFilter implementation

```
object BasicAuthFilter extends Filter with LazyLogging {
  
    private lazy val unauthResult = Results.Unauthorized.withHeaders(("WWW-Authenticate", 
    "Basic realm=\"myRealm\""))
    
    private lazy val passwordRequired = true
    private lazy val username = "someUsername"
    private lazy val password = "somePassword"
    
    private lazy val basicSt = "basic " 
    
    //This is needed if you are behind a load balancer or a proxy
    private def getUserIPAddress(request: RequestHeader): String = {
        return request.headers.get("x-forwarded-for").getOrElse(request.remoteAddress.toString)
    }
    
    private def logFailedAttempt(requestHeader: RequestHeader) = {
        logger.warn(s"IP address ${getUserIPAddress(requestHeader)} failed to log in, " +
            s"requested uri: ${requestHeader.uri}")
    }

    private def decodeBasicAuth(auth: String): Option[(String, String)] = {
        if (auth.length() < basicSt.length()) {
            return None
        }
        val basicReqSt = auth.substring(0, basicSt.length())
        if (basicReqSt.toLowerCase() != basicSt) {
            return None
        }
        val basicAuthSt = auth.replaceFirst(basicReqSt, "")
        //BESE64Decoder is not thread safe, don't make it a field of this object
        val decoder = new BASE64Decoder()
        val decodedAuthSt = new String(decoder.decodeBuffer(basicAuthSt), "UTF-8")
        val usernamePassword = decodedAuthSt.split(":")
        if (usernamePassword.length >= 2) {
            //account for ":" in passwords
            return Some(usernamePassword(0), usernamePassword.splitAt(1)._2.mkString)
        }
        None
    }

    def apply(nextFilter: (RequestHeader) => Future[Result])(requestHeader: RequestHeader): 
    Future[Result] = {
        if (!passwordRequired) {
            return nextFilter(requestHeader)
        }
        
        logger.info("BasicAuthFilter invoked")

        requestHeader.headers.get("authorization").map { basicAuth =>
            decodeBasicAuth(basicAuth) match {
                case Some((user, pass)) => {
                    if (username == user && password == pass) {
                        return nextFilter(requestHeader)
                    }
                }
                case _ => ;
            }
            logFailedAttempt(requestHeader)
            return Future.successful(unauthResult)
        }.getOrElse({
            logFailedAttempt(requestHeader)
            Future.successful(unauthResult)
        })

    }
}
```

The problem that I have here is that I need Injector here, in order to get some services and call them.

Ideally, I would like to have Filters that will be injected by Scaldi in the same way like services.
I already tried to initialize Filter by using dependency injection in Module, but it does not work, thereof Play does not see this kind of Filter and does not invoke it.

Can you help me with this Filter dependency injection problem?
Thanks,
Albert

**Comment by OlegIlyenko** [comment]
Sure, I will look at it a little bit later today. Are you using 2.4.0 or 2.3.x in this project? (the solution would be different based on the play version)

**Comment by OlegIlyenko** [comment]
In **Play 2.4.0** you need to define several classes (and you don't need to use `Global`):

    package filters

    import scala.concurrent.Future
    import play.api.http.HttpFilters
    import play.api.mvc.{Result, RequestHeader, Filter}
    import scaldi._
    
    class CustomFilter(implicit inj: Injector) extends Filter with Injectable {
      val ms = inject [MessageService]
    
      override def apply(nextFilter: (RequestHeader) => Future[Result])(requestHeader: RequestHeader): Future[Result] = {
        println("Doing filter business! " + ms.getGreetMessage("filter"))
        nextFilter(requestHeader)
      }
    }
    
    class MyFilters(implicit inj: Injector) extends HttpFilters with Injectable {
      override lazy val filters = Seq(inject [CustomFilter])
    }
    
    class FilterModule extends Module {
      binding to new MyFilters
      binding to new CustomFilter
    }

`CustomFilter` in this case is actual filter. `MyFilters` provides the list of active filters to the playframework. `FilterModule` is just another module that bind both of them.

When this is done, you need to add some configuration in the **conf/application.conf**:

    play.modules.enabled += filters.FilterModule
    play.http.filters = filters.MyFilters

The first line enables the module and the second line tells Play which filters it should use (because by default Play uses another class).

I probably need to add this in the documentation as well. 

BTW, you can find more info about this approach in the Play documentation:

https://www.playframework.com/documentation/2.4.x/ScalaHttpFilters

**Comment by albertshift** [comment]
Thank you!
