### ISSUE TITLE
Assets route

### ISSUE THREAD

**Issue by justjoheinz** [scaldi/scaldi-play-example#7]
I know this project example is probably a little bit outdated, but it exhibits the same problems, as with my more uptodate installation. Namely the assets route cannot be found:

```
http :9000/assets/123.css
HTTP/1.1 404 Not Found
Content-Length: 4899
Content-Type: text/html; charset=utf-8
Date: Mon, 07 Mar 2016 14:36:22 GMT

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Action not found</title>
...
```

Please let me know if there is anything I can do about it. Thanks!

**Comment by OlegIlyenko** [comment]
Hmmm... I'm not sure that it can be. i just double checked the application, and it works as expected. For example:

```bash
 $ curl http://localhost:9000/assets/stylesheets/main.css -v
* timeout on name lookup is not supported
* About to connect() to localhost port 9000 (#0)
*   Trying 127.0.0.1...
* connected
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /assets/stylesheets/main.css HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost:9000
> Accept: */*
>
< HTTP/1.1 200 OK
< ETag: "cca2fddc22573db526968820c2e063b6f02ab19f"
< Cache-Control: no-cache
< Last-Modified: Tue, 02 Apr 2013 18:25:02 GMT
< Content-Length: 0
< Content-Type: text/css; charset=utf-8
< Date: Mon, 07 Mar 2016 19:19:18 GMT
<
```

Maybe in your case file `123.css` does not exist in `public` or `app/assets` folders?

**Comment by justjoheinz** [comment]
Yes, you are right, the issue can be closed. 123.css does indeed not exist, but I would have expected a silent notfound error, not a whole stacktrace containing my routes files, as if the route indeed did not exist. But me thinks this is a play error how they log things. At least I wouldn't want this information to leak out of my application.

**Comment by OlegIlyenko** [comment]
:+1: I think Play only does this in the development mode. If you start an application in production mode, then it would be more silent about missing files.
